kind: pipeline
type: docker
name: ci/cd
volumes:
  - name: node_modules
    host:
      path: /root/$DRONE_REPO_NAME/node_modules
  - name: ssh_keys
    host:
      path: /root/.ssh
clone:
  disable: true
steps:
  - name: feishu
    image: registry.cn-shanghai.aliyuncs.com/zzf2001/foo-webhook
    settings:
      webhook:
        from_secret: webhook
      secret:
        from_secret: secret
  - name: clone
    image: alpine/git
    volumes:
      - name: ssh_keys
        path: /root/.ssh
    commands:
      - git clone $DRONE_GIT_SSH_URL .
      - git checkout $DRONE_COMMIT
  - name: build
    image: node:lts-alpine
    depends_on:
      - clone
    volumes:
      - name: node_modules
        path: /drone/src/node_modules
    commands:
      - pwd
      - ls -a
      - npm install
      - npm run doc:build
  - name: deploy
    image: appleboy/drone-scp
    depends_on:
      - build
    settings:
      host:
        from_secret: host
      port: 22
      username:
        from_secret: username
      password:
        from_secret: password
      target: /root
      source: ./dist
